default: &default
  adapter: postgresql
  encoding: utf8
  pool: 50
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: react_api_dev
  username: xiaohesong
  password:

staging:
  <<: *default
  database: react_api_staging
  username: postgres
  password: oss

production:
  <<: *default
  database: react_api_pro
  username: postgres
  password: oss
